spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/postgres?useSSL=false
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

boilerplate:
  app:
    jwtSecret: =======================Listriku=Spring===========================
    jwtExpirationMs: 86400000
    jwtCookieName: Listriku